#!/bin/bash

protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    read -p "You're about to push to main, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if [[ "$REPLY" == *"y"* ]] || [[ "$REPLY" == *"Y"* ]] 
    then
        exec make lint
        exit 0
    else
        exit 1
    fi
fi

exec make lint
